language: python
sudo: false
install:
  - pip install tox
script:
  - tox --skip-missing-interpreters -r -- -vv
env:
  - TOXENV=style
  - TOXENV=coverage
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
